name: Keep n8n Alive

on:
  schedule:
    - cron: "*/25 * * * *"  
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping n8n server
        run: |
          curl -s https://n8n-latest-s5ed.onrender.com > /dev/null
