name: Keep n8n Alive

on:
  schedule:
    - cron: "*/25 * * * *"  # every 25 minutes
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping n8n
        run: |
          curl -L ${{ secrets.N8N_URL }}
